# Generated by Django 5.2 on 2025-04-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GDELT", "GDELT"),
                            ("NEWSAPI", "NewsAPI"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("published_date", models.DateTimeField()),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                (
                    "sentiment_label",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_companies",
                    models.ManyToManyField(
                        related_name="news_articles", to="companies.company"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
    ]
