# Generated by Django 5.2 on 2025-04-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ticker_symbol", models.CharField(max_length=20, unique=True)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "United States"),
                            ("CN", "China"),
                            ("TW", "Taiwan"),
                        ],
                        max_length=2,
                    ),
                ),
                ("industry", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
    ]
